### ISSUE TITLE
ConcurrentModificationException on Respawn

### ISSUE THREAD

**Issue by xXTheBigBearXx** [blay09/BetterMinecraftChat#11]
Not sure if this is entirely caused by BMC but had the same crash twice with the same crash report: http://pastebin.com/kmQXgTZD

1.10 Unstable Version 4.11

**Comment by BlayTheNinth** [comment]
Looks like one of your installed mods is handling packets on the network thread. This can break all kinds of mods and it's hard to track down which mod is doing it.

**Comment by BlayTheNinth** [comment]
Issue in https://github.com/blay09/TwitchIntegration/issues/4
