### ISSUE TITLE
Tab style settings

### ISSUE THREAD

**Issue by Zero9o1o** [blay09/BetterMinecraftChat#16]
It would be nice if there was a combo styles. Like bottom and chat so you could filter like tells and have them pop up on the bottom but if you missed it you have a tab that show them so you can read what you missed and make it easy to reply to them.

**Comment by BlayTheNinth** [comment]
I think the usecase isn't common enough to justify making the message style setting more complex. The "temporary" message styles (Bottom, Side) are usually used for messages that are no longer relevant after they've disappeared.
