### ISSUE TITLE
gradle crash and some minor things

### ISSUE THREAD

**Issue by Iusgar** [blay09/BetterMinecraftChat#28]
Hi @Blay09,

your mod is great ((thumps up)). I'm working on a filter for one Server. It's working but there are some custom problems: the time and size of messages in the pop up areas (bottom and side) is to short/small and if you use the "outgoing prefixes" you aren't able to use other commands in these tabs. 

To fix this: I downloaded your latest code for 1.10.2 but gradle crashed -.- So I can't verify my changes. Probably this is my fault because I'm not so familiar with it, but it would be nice if you could tell me why or how ;-)

On the other hand I guess that many users would be glad to have an oppertunity to manage the size and time via the config-file (or anything else which is easy to change) ^^

Thanks for your work!

Iusgar

error-message
> Could not resolve all dependencies for configuration ':forgeGradleMcpData'.
> Could not resolve de.oceanlabs.mcp:mcp:1.10.2.
  Required by:
      project :
   > Could not resolve de.oceanlabs.mcp:mcp:1.10.2.
      > Could not get resource 'http://files.minecraftforge.net/maven/de/oceanlabs/mcp/mcp/1.10.2/mcp-1.10.2.pom'.
         > Could not GET 'http://files.minecraftforge.net/maven/de/oceanlabs/mcp/mcp/1.10.2/mcp-1.10.2.pom'.
            > Connect to files.minecraftforge.net:80 [files.minecraftforge.net/158.69.55.219] failed: Connection timed out: connect
   > Could not resolve de.oceanlabs.mcp:mcp:1.10.2.
      > Could not get resource 'https://libraries.minecraft.net/de/oceanlabs/mcp/mcp/1.10.2/mcp-1.10.2.pom'.
         > Could not GET 'https://libraries.minecraft.net/de/oceanlabs/mcp/mcp/1.10.2/mcp-1.10.2.pom'. Received status code 403 from server: Forbidden`

**Comment by BlayTheNinth** [comment]
This was fixed as part of the rewrite for Minecraft 1.11.2.
