### ISSUE TITLE
Changing setting using the config gui has issues

### ISSUE THREAD

**Issue by Zero9o1o** [blay09/BetterMinecraftChat#30]
If you change change options in the config gui of the mod options menu it will duplicated your chat channel thingies.

Minecraft Version: 1.10.2
Forge Version: 12.18.3.2254
Mod Version: 4.1.1

Additional info:
Pack: FTB Beyond, Version: 1.2.1

**Comment by BlayTheNinth** [comment]
This was fixed as part of the rewrite for Minecraft 1.11.2.
