### ISSUE TITLE
Ability to disable new message notifications

### ISSUE THREAD

**Issue by ZeekDaGeek** [blay09/BetterMinecraftChat#33]
It would be nice to be able to disable the new message notifications for Views. I enjoy having a [zeekdageek] tab so I can easily click through to it and be able to have /twitch #zeekdageek prepend every message but having it so it glows red all of the time at the bottom is slightly annoying.

**Comment by BlayTheNinth** [comment]
Wait, the "Show New Messages" option should already do this (at least for when the chat is closed).

**Comment by ZeekDaGeek** [comment]
Yeah the reason the bug report exists is because it doesn't work though. <;
