### ISSUE TITLE
Emotes Need Updating.

### ISSUE THREAD

**Issue by tehbasshunter** [blay09/BetterMinecraftChat#40]
The following emotes are simply returning their text form instead of desired emote:  
  
```
zResidentSleeper
zSwiftRage 
zHeyGuys
Clappy 
ClappyDerp 
ClappyHype
```

**Comment by BlayTheNinth** [comment]
Where are these emotes even from?

**Comment by tehbasshunter** [comment]
https://blog.twitch.tv/bring-the-zombie-apocalypse-to-twitch-7a5bf4ecff42

https://blog.twitch.tv/clips-turns-1-this-week-celebrate-with-us-20136c7e2cff

I also want to add zWutFace and zKappa as 2 other emotes that don't wanna work.

**Comment by BlayTheNinth** [comment]
They're crate-only and temporary for 2017, global emotes are only global emotes
