### ISSUE TITLE
How do you include timestamp as part of the "Output Format" field?

### ISSUE THREAD

**Issue by Schwaitz** [blay09/BetterMinecraftChat#52]
I have a specific view where I want to show the timestamp, but I don't want it for every chat message. Is there a special code (like {timestamp} or such) that I can include in the Output Format field?

**Comment by BlayTheNinth** [comment]
The $t variable in the output format should work.

**Comment by Schwaitz** [comment]
I tried that (here is what I have in the output): [Imgur Link](https://i.imgur.com/8vSXju5.png)

All that happens in chat is the literal characters "$t" and then the rest of the message. I'm on 1.12.2, by the way.

I scoured the code looking to see where it might be, and couldn't find anything.

**Comment by BlayTheNinth** [comment]
Sorry, it's `${t}`
