### ISSUE TITLE
There doesn't seem to be an updated Wiki, and all of the images from Curse are out of date

### ISSUE THREAD

**Issue by Schwaitz** [blay09/BetterMinecraftChat#53]
Hey there,

Sorry for creating two back-to-back issues, but I wanted to keep my other question seperate. Right now, the plugin is sort of in a  "figure everything out by yourself" state. Is it possible to work on a global wiki for all the specific things that might not be obvious?

Thanks

**Comment by BlayTheNinth** [comment]
Closing the issue here to get a clearer view of the issue tracker, but dedicated documentation pages for all of my mods (and CF page updates) are on the roadmap for right after I've caught up with all the ports and will be tracked [here](https://github.com/users/blay09/projects/6).
