### ISSUE TITLE
crash with MineTogether

### ISSUE THREAD

**Issue by ghost** [blay09/BetterMinecraftChat#54]
not sure who to report this to as 2 mods are mentioned.  But when I press / to go into chat I get instant crash, happened several times

MC 1.12.2
MineTogether 1.10.2.2.1.1
ChatTweaks 1.12.2.5.1.16
Forge 2757

https://pastebin.com/03Sz5GYE

**Comment by BlayTheNinth** [comment]
MineTogether fully replaces the chat, and so does Chat Tweaks, so the two mods are incompatible to each other - only one of them can work at a time.
