### ISSUE TITLE
Local emotes need more configuration

### ISSUE THREAD

**Issue by twilight-sparkle-irl** [blay09/BetterMinecraftChat#56]
* Aliases
I want to have a 🤔 emote that works with both `🤔` in chat and `:thinking:` in chat. There appears to be no way to do this. 
* Filenames
Even if I ditched using `🤔`, there'd be no way to name an emote `:thinking:` because on windows you cannot have a : in the filename. 
* SVG support
This one isn't as important, but it'd be nice uwu

Thank you for your time!

**Comment by BlayTheNinth** [comment]
The next version will allow you to specify aliases in the config file in `🤔=thinking.png` format.

SVG support however is not really worth the additional external dependency.
