### ISSUE TITLE
Settings and Highlights

### ISSUE THREAD

**Issue by Dar-krusos** [blay09/BetterMinecraftChat#60]
As of my latest testing from 18/10/18, highlights don't work on (modded?) servers. Settings also do not stay changed except if edited via the .cfg file.

**Comment by EnragedN3wb** [comment]
To add to this, some settings are actually missing from the configs, so editing the configs doesn't even always work around this. :(

The "Include Twitch Smileys" setting being one example.

**Comment by BlayTheNinth** [comment]
Closing since 1.12 is no longer supported and the eventual port to 1.16 will have a rewrite of the configuration that will solve this on its own.
