### ISSUE TITLE
Incompatibility with MineTogether

### ISSUE THREAD

**Issue by destroina** [blay09/BetterMinecraftChat#62]
hi, used chatweaks and twitch integration for a couple of times in this new modpack, no issues, since then been getting this crash, game goes fine and can log in, can play too, when i press chat key it freezes and crash. hope it isint a dumb mistake of me.
[crash-2019-04-17_18.08.03-client.txt.zip](https://github.com/blay09/ChatTweaks/files/3090788/crash-2019-04-17_18.08.03-client.txt.zip)

i dunno if this file worked, reach me in email or Zeek's Discord if anything needed

**Comment by BlayTheNinth** [comment]
Chat Tweaks is not compatible with MineTogether since MineTogether adds its own chat replacement, you can safely remove MineTogether though if you're not using it.

**Comment by destroina** [comment]
thank you!! GeekHeart
