### ISSUE TITLE
Minecraft 1.16

### ISSUE THREAD

**Issue by BlayTheNinth** [blay09/BetterMinecraftChat#71]
Mostly waiting on Forge to re-implement the config gui.

**Comment by Boobies** [comment]
No chance of doing a version for Fabric rather than Forge?

**Comment by danisaacs** [comment]
Any update on 1.14 support?

**Comment by Boobies** [comment]
It's probably going to have to be 1.15 at this point. However, it seems quite certain that this project has been abandoned so the only hope is that someone else has the time to fork it and take over on that front.

**Comment by BlayTheNinth** [comment]
Closing so I don't have to keep changing the title over and over and over and over and over, port will come eventually
