### ISSUE TITLE
Only a few FFZ emotes available

### ISSUE THREAD

**Issue by ohmree** [blay09/BetterMinecraftChat#75]
I'm using the latest Cursefore release (which isn't very recent) and it seems like there are only a few global FFZ emotes that display and show up in the menu (at least that's what I think they are).

I noticed a few issues here on the repo that seem to be related to API usage so my hypothesis is that the stable CT release is using an unsupported API for BTTV and Twitch emotes, but I can't confirm or deny it by using a version built from master since the link to your Jenkins is broken. 

Would Github CI maybe work for this repo? (for people like me who don't want to grab the entire JDK just for building one mod)
If not, is there an ETA for a new version?

Thanks for developing this mod, and thanks in advance if you reply.

**Comment by ohmree** [comment]
Well, I tried setting up Travis but it turns out that it discards build artifacts by default.  
Since I couldn't get the Travis CLI tool to recognize my repo in order to set up Github releases I just gave up and built it in WSL.  
I haven't tried it yet but here's the build if anyone's interested:
[ChatTweaks_1.12.2-5.1.0.zip](https://github.com/blay09/ChatTweaks/files/4359026/ChatTweaks_1.12.2-5.1.0.zip)

**Comment by ohmree** [comment]
With the version I built from the 1.12.2 branch I now get proper BTTV emotes for the channel I selected (xQcOW) but still no global Twitch emotes or channel FFZ emotes.

Oh well, at least that's something.

**Comment by BlayTheNinth** [comment]
Since emote APIs continuously have breaking changes, I doubt most emotes of the 1.12.2 version will work for much longer in general. I'll update to the latest APIs once I get to the 1.15.2 port, but unfortunately there won't be any backports to earlier versions.

**Comment by BlayTheNinth** [comment]
With the coming 1.16 port, emotes should become much more stable and in most cases no longer randomly stop working based on external factors thanks to #67. 

Closing this one to get a clearer view of open issues.
