### ISSUE TITLE
Want to do a simple filter on username, can't get it to work

### ISSUE THREAD

**Issue by sanomi78** [blay09/BetterMinecraftChat#86]
### Minecraft Version

1.12.x

### Mod Loader

Forge

### Mod Loader Version

14.23.5.2860

### Mod Version

5.1.25

### Describe the Issue

I can't get the filtering to work.

What i want to do is filter certain players into their own tab (let's call it the Ignore-tab for now). I am trying to understand regex but i have no idea.

So if i want to filter a player called Sungod into the tab called Ignore - what Regex code should i be using?
And if i want to add a player called Moongod too, how should i go about that?

Thanks for the help!

**Comment by BlayTheNinth** [comment]
To have Sungod only appear on the Ignore Tab, you would use the pattern: `<(Sungod)> (.+)`
To also add Moongod, you would add it using an or symbol (`|`): `<(Sungod|Moongod)> (.+)`

Make sure to set the view as "Exclusive" to prevent the message from also showing up on the main tab.

**Comment by sanomi78** [comment]
First of all sorry for labeling it bug when it clearly isn't. I didn't have a better option.

Second: thank you very much - this helps a lot!
